version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /app/node_modules/bcrypt/
      - /dev/null/:/api/node_modules/bcrypt/
      - /usr/src/app/node_modules/
volumes:
  node_modules: